CREATE TABLE categorias (
    id_categoria INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    nome VARCHAR(255) NOT NULL UNIQUE
    rateio TINYINT UNSIGNED NOT NULL DEFAULT 0 CHECK (rateio BETWEEN 0 AND 100);
);